### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#1]
As a **Visitor**,

I want to **create a user account**,

so that **I can use the app**

### Acceptance Criteria

1. A Visitor can create an account with a username and password

### Tasks

- [ ] create SignUp form & add it to App.js
- [ ] style SignUp page
- [ ] test signup functionality
