### ISSUE TITLE
USER STORY: Color palette

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#100]
As a **Developer**,

I want to **create a custom color palette for the app**,

so that **users interacting with the app have a positive user experience**

### Acceptance Criteria

1. A custom color palette is selected to fit the theme of the app
2. On top of purely easthetic use, task status is also indicated by colors
3. Colors are tested for sufficient contrast (WebAIM)
### Tasks

- [x] select color palette
- [x] perform accessibility testing of text+background contrasts with WebAIM
- [x] adjust hues if necessary
