### ISSUE TITLE
USER STORY: Put TaskForm into separate component

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#102]
As a **Developer**,

I want to **Create code that adheres to the DRY principle**,

so that **avoid copy+paste errors, improve maintainability & auditability**

### Acceptance Criteria

1. The TaskForm component contains logic & rendering that can be used for both TaskCreateForm & TaskEditForm
2. The TaskForm component has conditional logic to accommodate differences between TaskCreateForm & TaskEditForm
3. The TaskForm component gets the appropriate props to make use of conditional logic

### Tasks

- [x] move TaskForm into separate component
- [x] import TaskForm TaskCreateForm
- [x] in TaskForm, conditionally render elements that should be different between TaskCreateForm & TaskEdit Form
- [x] import TaskForm into TaskEditForm
- [x] pass appropriate `prop` from TaskEditForm to TaskForm to indicate the use case & trigger conditional rendering
