### ISSUE TITLE
USER STORY: Finalize flow & routing for the app

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#111]
As a **Developer**,

I want to **implement an intuitive and smooth user flow between different parts of the app**,

so that **user experience is as good as possible**

### Acceptance Criteria

1. User journey with possible paths is documented
  - Pages available to Logged-out Users:
    - Landing (default)
    - Signin
    - Signup
  - Pages available to Logged-in Users:
    - Tasks 
      - TaskKanban (default)
      - TaskList
      - TaskDetail
      - TaskCreate
      - TaskEdit
      - TaskDelete (implemented with modal on TaskKanban/List/Detail)
    - Profiles/Users
      - ProfileList/Teammates
      - ProfileDetail
      - ProfileEdit
      - Username Edit
      - Password Edit

2. Routing & redirecting implemented accordingly

### Tasks

- [x] implement routing & redirecting accordingly
  - [x] redirect Logged-in Users from landing page in `Landing`
  - [x] redirect Logged-out Users from TaskTab & Kanban pages (only need to set redirect in `TaskTabs`, as `TaskKanban` is called as its child)
  - [x] redirect Logged-in Users from Team page in `ProfileList` (needs to be converted into a function OR the `Landing` component should be imported as the `else` case of the currently implemented logic of only showing the contents if there is a `currentUser`)
  - [x] redirect Logged-in Users from ProfileDetail page in `ProfileList`
- [x] remove superfluous routes from `App.js`
- [x] make Kanban Navbar link active on home page

Related: #126

**Comment by blahosyl** [comment]
Blocked by #51
