### ISSUE TITLE
USER STORY: Tabbed filtering of ProfileList

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#112]
As a **Logged-in User**,

I want to **Filter profiles on the profile list view**,

so that **I can have an overview of profiles with specific properties**

### Acceptance Criteria

1. Logged-in Users can filter the profile list:
  - owners of tasks assigned to me
  - assignees of tasks watched by me
  - assignees of tasks created by me
  - all
2. The filtering is presented in a tab format
3. The search bar only returns results from the selected tab

### Tasks

- [x] create `ProfileTab` component with Bootstrap `Tab`
- [x] import & connect `ProfileTab` in `App.js`
- [x] use the `ProfileList` component in each tab with the appropriate filter
