### ISSUE TITLE
USER STORY: Tabbed Kanban view for tasks

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#113]
As a **User**,

I want to **have separate Kanban Boards for differently filtered tasks**,

so that **I can concentrate on relevant information**

### Acceptance Criteria

1. There is a Kanban board for each tab designed in #58 
2. This view does not display the list of profiles, only a link to the ProfileList page

### Tasks

- [x] Use the `TaskKanban` component within the `TaskTab` component
- [x] conditionally render `TaskList` vs `TaskKanban`
- [x] conditionally render ProfileList in the right side panel & adjust Task column width
- [x] in `App.js`, pass `list` prop to govern conditional rendering
- [x] in `TaskTabs`, destructure `list` prop to be used
