### ISSUE TITLE
USER STORY: Show count on filtering/search views

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#114]
As a **Loggein-in User**,

I want to **See how many results I got when I filter/search the list of tasks or profiles**,

so that **can better estimate and plan work.**

### Acceptance Criteria

1. TaskList views show count of tasks in each tab/column
2. ProfileList views show count of tasks in each tab

#### Task List in Profile Detail 

- [x] add `watched_count` and `owned_count` to Profiles API
- [x] show counts in tabs

#### Task List main views

- [x] use `ProfileDataContext.js` to get the relevant fields from the Profile serializer/view to this component, so that they can be displayed
- [x] show `assigned_count`, `watched_count` and `owned_count` in the relevant tabs
- [x] refresh list of tasks

**Comment by blahosyl** [comment]
API changes:
- [rename tasks_count to assigned_count](https://github.com/blahosyl/task-manager-api/commit/e60b9649bdd70298a0d5fae5ca48a9d6e9bb45d0)
- [add watched_count field to Profiles](https://github.com/blahosyl/task-manager-api/commit/7e12403299e104e21f5f8bfb78e2117a08414d83)
- [add owned_count field to Profile](https://github.com/blahosyl/task-manager-api/commit/16ae9d8b9b9c85e3f60ff35efd525e3f812cbe7e)

**Comment by blahosyl** [comment]
Ask mentor what the best way is to implement getting the count of all tasks (if at all).

**Comment by blahosyl** [comment]
Frontend implementation continued in #124
