### ISSUE TITLE
USER STORY: Show more information on full Profile List

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#117]
As a **Logged-in User**,

I want to **see more information on the full Profile List than on the sidebar Profile List**,

so that **can see more profile information at a glance**

### Acceptance Criteria

1. `role` and `pronoun` fields appear for each user on full-page Profile List (unless they are empty)
2. These fields do not appear on the Profile List in the sidebar.

### Tasks

- [x]  in `App.js`, pass `full` prop to full-page `ProfileList`
- [x] in  `ProfileList`, destructure the prop: `const { full } = props;`
- [x]  in `ProfileList`, pass `full` prop to  `Profile`
- [x] in  `Profile`, destructure the prop: `const { full } = props;`
- [x] conditionally render `role` and `pronouns` on full-page Profile List
