### ISSUE TITLE
USER STORY: View login status

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#12]
As a **User**,

I want to **view my login status**,

so that **I know if I need to log in or not**

### Acceptance Criteria

1. Login status of the user is displayed in the NavBar
2. Signup & Signin icons are not displayed for logged-in users

### Tasks

- [x] get current user when component mounts
- [x] make current user accessible to Child components with Context
- [x] display NavBar icons depending on Login status
