### ISSUE TITLE
USER STORY: Adjust all app colors/shapes

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#120]
As a **Developer**,

I want to **harmonize all visual elements of the app **,

so that **the result is consistent and visually pleasing**

### Acceptance Criteria

1. Nav links & icons conform to color palette
2. In-text links conform to color palette
3. Backgrounds conform to color palette

### Tasks

- [x] adjust logo
- [x] adjust favicon
- [x] adjust nav icons incl. hover
- [x] adjust links incl. hover
- [x] adjust app background
- [x] adjust button styling
- [x] adjust modal styling
- [x] adjust Signin form styling
- [x] adjust Signup form styling
- [x] adjust Task Create/Edit form styling
- [x] adjust ProfileEdit form styling
- [x] adjust Username form styling
- [x] adjust Password form styling
- [x] #136
- [x] set different styles for Submit & Cancel buttons

- [x] #137
