### ISSUE TITLE
USER STORY: Refresh access tokens

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#13]
As a **Logged-In User**,

I want to **maintain my logged-in status until I choose to log out**,

so that **I do not have to log in too frequently**

### Acceptance Criteria

1. User gets a refresh token valid for a day
2. When the access token expires and the refresh token is valid, the access token is refreshed in the background

### Tasks

- [x] create axios interceptors `axiosRes` & `axiosReq`
- [x] set `axiosRes` to refresh `access_token` if it gets an 401 error
- [x] add `axiosRes` to `handleMount()`
- [x] set `axiosReq` to always refresh access token before making a request
- [x] check if user is logged in after some inactivity (more than 5 min but less than 24 hours
