### ISSUE TITLE
USER STORY: Customize images

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#130]
As a **Developer**,

I want to **customize images in the app**,

so that **they fit the design theme**

### Acceptance Criteria

1. All images fir the color palette & theme of the app

### Tasks

- [x] add background image to "not found" page (candidates in Downloads folder)
- [x] change not-found asset
- [x] change upload asset
