### ISSUE TITLE
USER STORY: README | Features

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#145]
As a **Developer**,

I want to **document the project's features**,

so that **readers can get a feel for the scope and implementation**

### Acceptance Criteria

1. All items below are described in the README

#### General

- [x] nav bar mobile
- [x] nav bar desktop
- [x] footer
- [x] landing page
- [x] singin page
- [x] singup page

#### Tasks
- [ ] kanban page
- [x] task list page
- [x] search
- [x] filtering with tabs
- [x] task detail page
- [x] create task
- [x] edit task
- [x] delete task
- [x] watch/unwatch

#### Comments
- [x] add comment
- [x] edit comment
- [x] delete comment
 
#### `Profiles`

- [x] profile list page
- [x] profile detail page
- [x] edit profile
- [x] edit username
- [x] edit password

#### Other

- [x] future features
- [x] Code features
