### ISSUE TITLE
USER STORY: Manual feature testing

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#150]
As a **Developer**,

I want to **manually test all features of the project**,

so that **I can make sure everything works as intended and uncover any bugs**

### Acceptance Criteria

1. All features of the project are manually tested
2. Any bugs are documented in an Issue

#### General

- [x] nav bar mobile
- [x] nav bar desktop logged in user
- [x] nav bar desktop not logged in user
- [x] footer
- [x] landing page
- [x] singin page
- [x] singup page

#### Tasks

- [x] kanban page
- [x] task list page
- [x] search
- [x] filtering with tabs
- [x] task detail page
- [x] create task
- [x] edit task
- [x] delete task

#### Comments
- [x] add comment
- [x] edit comment
- [x] delete comment
 
#### `Profiles`

- [x] profile list page
- [x] profile detail page
- [x] edit profile
- [ ] edit username
- [x] edit password
