### ISSUE TITLE
USER STORY: Create task without image

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#21]
As a **User**,

I want to **create task without an image**,

so that **I can focus on the task description instead**

### Acceptance Criteria

1. The TaskCreateForm accepts inputs without an image file.
2. The API does not add a placeholder image to the Task object
3. Tasks without images are shown without a placeholder.

### Tasks

- [x] allow FE validation to upload a new task without an image: 
`image && formData.append("image", imageInput.current.files[0]);`
- [x] remove default image from API Task model `image` field & allow `null` as a value
- [x] change `task` serializer in API to only validate the image field if there is an input
- [x] change `Task.js` in FE to only show the image field if there is an image

**Comment by blahosyl** [comment]
Tried and failed:

- add `null=True` to the `Post` model in the API (DRF walkthough repo)
- in FE, add conditional: to `handleChange()`:
  ```
  image !== ""
      ? formData.append("image", imageInput.current.files[0])
      : formData.append("image", "")
  ```
- tried the above with
  - ` image != ""`
  - ` image`
  - `formData.append("image", null)`

**Comment by blahosyl** [comment]
API commits:

- [remove default image from API Task model `image` field & allow `null` as a value](https://github.com/blahosyl/task-manager-api/commit/3868c4a524b826a5e2bf2d8e2bddc48fd7d3adf3)
- [change `task` serializer in API to only validate the image field if there is an input](https://github.com/blahosyl/task-manager-api/commit/986161766b5b34483558c43c579e7e891fb06646)
