### ISSUE TITLE
USER STORY: Get list of users for Assignee dropdown

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#22]
As a **User**,

I want to **see the list of users in the *Assigned to* dropdown**,

so that **I can choose the right assignee**

### Acceptance Criteria

1. The **Assigned to** dropdown shows all available users
2. The selected value is recorded in the newly created task in the DB

### Tasks

- [x] fetch profiles & show username in assignee dropdown
- [x] add `key` and `value` to `select` dropdown `option`. 
  The Profile ID is user here. Since a profile is automatically created whenever a user is created, profile ID and user ID should be the same.
- [x] conditionally render assignee name in dropdown
    - show first name, last name or both if they exist
    - otherwise, show username

**Comment by blahosyl** [comment]
Contacted tutoring regarding an error when trying to display profiles on the assignee dropdown.

![Image](https://github.com/user-attachments/assets/c801482a-75cd-4ff6-886b-2245f8c35e0d)

Oisin pointed out that the dropdown might try to display the names before the `profiles` object has finished fetching, and suggested to add a conditional to the form: 

```
{profiles.length && (
            <>
              {profiles.map((profile) => {
                return <option 
                  key={profile.id} 
                  value={profile.id}>
                   {profile.owner}
              </option>
```

This solved the issue.
