### ISSUE TITLE
USER STORY: View individual task pages

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#23]
As a **Logged-in User**,

I want to **view individual task pages**,

so that **can see all task attributes**

### Acceptance Criteria

1. Logged-in Users can see a TaskDetail page with all task attributes
2. Task page is available by URL: `/tasks/:id` (later from task list #4 )

### Tasks

- [x] add `TaskDetail` component, import to `App.js` & create route
- [x] fetch task from API & log it to console
- [x] add starter code for Task component & style
display task with watcher count & "Watch" placeholder
- [x] import React components
  - [x] Card
  - [x] Media
  - [x] OverlayTrigger
  - [x] Tooltip
- [x] desctructure task props
- [x] define `currentUser` & `isOwner` constants
- [x] replace placeholder `div` with card, display attributes
