### ISSUE TITLE
USER STORY: Watch/unwatch tasks

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#24]
As a **Logged-in User**,

I want to **watch/unwatch tasks**,

so that **I can update which tasks appear in my *Watched* feed**

### Acceptance Criteria

1. The TaskDetail page has a clickable "eye" icon, where users can watch/unwatch tasks
2. The icon changes color depending on whether the Logged-in User already watches the post

### Tasks

- [x] make API request & update Task data if successful 
- [x] write `handleWatch` & `handleUnwatch` functions
- [x] if `watched_id` exists (task is watched), `handleUnwatch()` on clicking the eye icon
- [x] if `watched_id` doesn't exist (task is not watched) & there is a logged in user (`currentUser`), `handleWatch()` on clicking the eye icon

**Comment by blahosyl** [comment]
Getting a 400 error

![Image](https://github.com/user-attachments/assets/8481e9e2-b025-4afd-82c0-4ad82670d7fd)

**Comment by blahosyl** [comment]
Unwatching works without issues, only watching is a problem.

**Comment by blahosyl** [comment]
I contacted tutoring reagarding the 400 issue with watching tasks.

After tutor Osisin showed me how I can see Django errors in the network tab of Chrome Dev tools, I discovered that the `watcher` endpoint was missing the `watched:id`.


![Image](https://github.com/user-attachments/assets/2d282584-7c25-4114-8572-1fac8cfe996c)


Changing `{task: id}` to `{watched:id}` in the API call in `Task.js` solved the issue ([dbff1d1](https://github.com/blahosyl/task-manager-frontend/commit/dbff1d1a7714e5314e63e4fa64a5cc3d3db5645c)).
