### ISSUE TITLE
USER STORY: Continuous scrolling/infinite scroll

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#27]
As a **Use**,

I want to **browse tasks continuously**,

so that **I do not have to click a button to load more tasks**

### Acceptance Criteria

1. Posts load automatically without the user having to click "next"
2. Spinner is showing while posts are loading

### Tasks

- [x] install infinite scroll component `npm install react-infinite-scroll-component`
- [x] create `fetchMoreData` in utils
- [x] in `TaskList` component, call `Task` inside `InfiniteScroll`, with `fetchMoreData` in the `next` prop
