### ISSUE TITLE
USER STORY: Continuous scrolling/infinite scroll for comments

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#30]
As a **Use**,

I want to **browse comments continuously**,

so that **I do not have to click a button to load more comments**

### Acceptance Criteria

1. Comments load automatically without the user having to click "next"
2. Spinner is showing while comments are loading

### Tasks

- [x] install infinite scroll component `npm install react-infinite-scroll-component`(if not already installed)
- [x] create `fetchMoreData` in utils
- [x] in `CommentList` component, call `Comment` inside `InfiniteScroll`, with `fetchMoreData` in the `next` prop

**Comment by blahosyl** [comment]
Blocked by #42

**Comment by blahosyl** [comment]
#42
