### ISSUE TITLE
USER STORY: Edit own profile

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#39]
As a **Logged-in User**,

I want to **edit my own profile**,

so that **can correct the data when necessary**

### Acceptance Criteria

1. Logged-in Users can edit their own profile, changing the following fields:
   - `firstname`
   - `lastname`
   - `role`
   - `pronouns`
   - `about`
   - `image`
2. Logged-in Users cannot edit other users' profiles
3. Users who are not logged in cannot edit any profiles

### Tasks

- [x] add `ProfileEditDropdown`
  - add `ProfileEditDropdown` & import `useHistory` in `MoreDropdown.js`
  - add `ProfileEditForm`
  - use `ProfileEditDropdown` in `ProfileDetail.js`
 - [x] add route using `ProfileEditForm` in `App.js`
 - [x] add all Profile fields to `ProfileEditForm`:
   - `firstname`
   - `lastname`
   - `role`
   - `pronouns`
   - `about`
- [x] check that image upload functionality is included in `ProfileEditForm`

#### Testing

- [x] Logged-in Users can edit their own profile (all fields specified below)
- [x] Logged-in Users cannot edit other users' profiles
- [x] Users who are not logged in cannot edit any profiles
