### ISSUE TITLE
USER STORY: View list of tasks

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#4]
As a **Logged-In User**,

I want to **view a list of all tasks**,

so that **have an overview of tasks**

### Acceptance Criteria

1. Logged-In Users can view a list of all tasks
2. List shows the following task attributes:
  - title
  - assignee
  - priority
  - due date
  - status

### Tasks

- [x] add TaskList starter code & styling
- [x] add routes for home page (all tasks), watched & assigned to user
- [x] display all tasks on home page
- [x] display filtered tasks on Watched/Assigned pages

**Comment by blahosyl** [comment]
Related commit: https://github.com/blahosyl/task-manager-frontend/commit/37df699fbf8a9cddbbf521f37d8932c0a394608f
