### ISSUE TITLE
USER STORY: View minimal landing page

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#5]
As a **Visitor**,

I want to **view a minimal landing page**,

so that **I can learn about the app and sign up**

### Acceptance Criteria

1. The landing page shows a basic description of the app
2. It includes a link to the signup page
3. It is responsive on all viewport sizes in scope (min. height 320 px)

### Tasks

- [x] create `Landing.js` in `components`
- [x] create `Landing.module.css` in `styles`
- [x] import & use `Landing.js` in `App.js`
- [x]  import & use `Landing.module.css` in `Landing.js`

**Comment by blahosyl** [comment]
https://github.com/blahosyl/task-manager-frontend/commit/89134821a2c1c03e221ecf12e4db6112626f19ea
