### ISSUE TITLE
USER STORY: View tasks on Kanban board

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#57]
As a **Logged-in User**,

I want to **View tasks on a Kanban board**,

so that **I have a better overview of task status**

### Acceptance Criteria

1. Logged-in Users can view tasks on a Kanban board
2. Columns of the Board correspond to task status

### Tasks

- [x] create TaskKanban component based on TaskList
- [x] import it to `App.js` & add route
- [x] create corresponding CSS file
- [x] import the CSS file of TaskList (this styles the search bar)
- [x] in TaskKanban, create 3 columns, and call the `Task` component in each with a different conditional based on task status:
   ```
  children={tasks.results.map((task) => (
    task.status === "DONE" && (
      <Task key={task.id} {...task} setTasks={setTasks} />
    )
  ))}
  ```
- [x] remove Teammates component
- [x] make column container full width
- [x] add Teammates link to either NavBar or next to search bar
- [x] implement horizontal scrolling
- [x] ~~make board responsive~~ #107 
- [x] style board

**Comment by blahosyl** [comment]
Blocked by #25
