### ISSUE TITLE
USER STORY: Tabbed filtering of tasks on the task list view

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#58]
As a **Logged-in User**,

I want to **Filter tasks on the task list view**,

so that **I can have an overview of tasks with specific properties**

### Acceptance Criteria

1. Logged-in Users can filter the task list:
  - assigned to me
  - watched by me
  - created by me
  - all
2. The filtering is presented in a tab format
3. The search bar only returns results from the selected tab

### Tasks

- [x] create `TaskTab` component with Bootstrap `Tab`
- [x] import & connect `TaskTab` in `App.js`
- [x] use the `TaskList` component in each tab with the appropriate filter
