### ISSUE TITLE
USER STORY: View social media/contact info

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#64]
As a **Visitor**,

I want to **view social media/contact info of the Site Admin**,

so that **I can find out more about them & contact them**

### Acceptance Criteria

1. The Site Admin's GitHub & LinkedIn profile link is visible in the footer

### Tasks

- [ ] create `Footer.js` in `components`
- [ ] create `Footer.module.css` in `styles`
- [ ] import & use `Footer.js` in `App.js`
- [ ]  import & use `Footer.module.css` in `Footer.js`
