### ISSUE TITLE
USER STORY: Infinite scroll for Profiles

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#66]
As a **Use**,

I want to **browse profiles continuously**,

so that **I do not have to click a button to load more profiles**

### Acceptance Criteria

1. Profiles load automatically without the user having to click "next"
2. Spinner is showing while profiles are loading

### Tasks

- [x] install infinite scroll component `npm install react-infinite-scroll-component`(if not already installed)
- [x]create `fetchMoreData` in utils (if not already created)
- [x] in `ProfileList` component, call `Profile` inside `InfiniteScroll`, with `fetchMoreData` in the `next` prop

**Comment by blahosyl** [comment]
Blocked by #59

**Comment by blahosyl** [comment]
Contacted tutor support: John determined that InfiniteScroll was not even triggering. He tried several remediations, including hardcoding the dataLength, destructuring the setProfileData function and removing my conditional test that cuts out the one profile, but nothing worked.

**Comment by blahosyl** [comment]
After some more searching on Stackoverflow, I found some suggestions that had to do with fixing the height of InfiniteScroll (or its container div.)

Adding `height={400}` to the props of `InfiniteScroll` finally triggered the loader and retrieved the next page of profile objects from the API. However, these are not rendered, and the component shows the spinner indefinitely.



![Image](https://github.com/user-attachments/assets/a68a9fc7-fdc8-498b-bdc7-3a1ebf36df59)



![Image](https://github.com/user-attachments/assets/af89c326-54b6-4493-84c5-288a6e52958d)

**Comment by blahosyl** [comment]
As for the `next` prop of `InfiniteScroll`, `fetchMoreData(useProfileData, useSetProfileData)` does not make the right api call, but both `fetchMoreData(profileList, useSetProfileData)` and `fetchMoreData(profileList, useProfileData)` do.

However, `profileList.results` is not updated.

**Comment by blahosyl** [comment]
An  [alternative fix to InfiniteScroll not triggering](https://stackoverflow.com/a/76741176) is to set the following CSS properties on its container. 
```
overflow: hidden; /* Hide any overflow beyond the content's size */
height: 100vh; /* Set the height equal to the viewport height to limit scrolling */
```

The rest of the suggestion does not seem to change much.

**Comment by blahosyl** [comment]
[Solution by John Rearden](https://github.com/johnrearden/task-manager-frontend/commit/ec8e98e9cdbad1159501fc5b92dc2f23cb7975a4#diff-0c6bbc781d2ac66b877546123b753fb2f69957838aea8419d7c2bc46740d6aea): use a custom API call instead of using `fetchMoreData()`

**Comment by blahosyl** [comment]
Make ProfileList div scrollable
