### ISSUE TITLE
USER STORY: Infinite scroll for Projects

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#67]
As a **Use**,

I want to **browse projects continuously**,

so that **I do not have to click a button to load more projects**

### Acceptance Criteria

1. Projects load automatically without the user having to click "next"
2. Spinner is showing while projects are loading

### Tasks

- [x] install infinite scroll component `npm install react-infinite-scroll-component`(if not already installed)
- [ ] create `fetchMoreData` in utils
- [ ] in `ProjectList` component, call `Project` inside `InfiniteScroll`, with `fetchMoreData` in the `next` prop

**Comment by blahosyl** [comment]
Blocked by #49 & #50
