### ISSUE TITLE
USER STORY: NavBar

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#7]
As a **Visitor**,

I want to **view a NavBar from every page**,

so that **I can navigate easily between pages**

### Acceptance Criteria

1. A NavBar is visible on all pages of the ap
2. It contains links to signing up/in/out

### Tasks

- [x] create NavBar component & add it to `App.js`
- [x] style NavBar
- [x] add sign up/in/out icons (depending on logged-in status: #12)
- [x] add "Create task" nav item
- [x] add "Watched" nav item
- [x] add "Assigned to me" nav item
- [x] auto-close toggle when an icon is clicked

**Comment by blahosyl** [comment]
- [create NavBar componend & add it to App.js #16](https://github.com/blahosyl/task-manager-frontend/commit/6c47cce7dc0734dc4e0170e5b4d8a866b0f25485)
- [add bootstrap navbar #16](https://github.com/blahosyl/task-manager-frontend/commit/6aafc3a931e94fe1784f258dbaa1d43363008204)
- [add Fontawesome icons to navbar #16](https://github.com/blahosyl/task-manager-frontend/commit/c0029e81733b6f2a21d366e13cbcc33340001acc)
- [add NavBar styling #17](https://github.com/blahosyl/task-manager-frontend/commit/cc1564311b13d5a073bdfbb532895174df264e15)
- [fix code formatting](https://github.com/blahosyl/task-manager-frontend/commit/82262ae20fa9850708700b5b6062718a62bc62fe)
