### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#77]
## FE

- [x] [remove Strict Mode](https://github.com/blahosyl/moments-walkthrough/commit/d8d52010fb2a049fa66187e318de587f97350a2b)
- [x] remove console logs
- [x] Git commit
- [x] Git push
- [x] redeploy Heroku app

## API

- [x] `DEBUG = False`
- [x] Git commit
- [x] Git push
- [x] redeploy Heroku app
