### ISSUE TITLE
USER STORY: No token refresh for logged out users

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#78]
As a **Visitor**,

I want to **use the app without unnecessary access token refresh attempt**,

so that **my app usage is streamlined**

### Acceptance Criteria

1. The app does not try to refresh tokens for logged out users

### Tasks

- [x] install `jwt-decode`: `npm install jwt-decode`
- [x] in `utils.js`, define the following:
  - [x] import `jwt-decode`
  - [x] `setTokenTimestamp`: store token timestamp in local storage 
  - [x]  `shouldRefreshToken`: Boolean: should the user's token be refreshed or not: it will only be refreshed for a Logged-in User
  - [x] `removeTokenTimestamp`: remove token timestamp from local storage
 
- [x] add token timestamp to local storage when the user signs in:
  - [x]  in `SignInForm`, `import { setTokenTimestamp } from "../../utils/utils";
  - [x]  add `setTokenTimestamp(data);` to the `try` block

- [x] in `CurrentUserContext.js`, check if the token should be refreshed:
  - [x] import `shouldRefreshToken` from `utils`
  - [x] put the `try` block in `useMemo` inside a conditional:
    ```
    useMemo(() => {
      axiosReq.interceptors.request.use(
        async (config) => {
          if (shouldRefreshToken()) {
            try {
              await axios.post("/dj-rest-auth/token/refresh/");
            } catch (err) {
              setCurrentUser((prevCurrentUser) => {
                if (prevCurrentUser) {
                  history.push("/signin");
                }
                return null;
              });
              return config;
            }
          }
          return config;
        },
        (err) => {
          return Promise.reject(err);
        }
      );
    ```

- [x] remove token timestamp from storage when user logs out or refresh token expires:
   - [x] `NavBar.js`
     - [x] import `removeTokenTimestamp` from `utils`
     - [x]  under the `try` block, add `removeTokenTimestamp();`

   - [x] `CurrentUserContext.js`
      - [x] import `removeTokenTimestamp` from `utils`
      - [x] under refresh interceptor, add `removeTokenTimestamp();`
      - [x] under response interceptor  add `removeTokenTimestamp();`

#### Testing

- [x] add token timestamp to local storage when the user signs in
  - In Developer Tools, go to **Application** > **Storage** > **Local storage** > `app name`
  - sign in
  - check that `refreshTokenTimestamp` is added to local storage

![Image](https://github.com/user-attachments/assets/996e9cd6-07cc-4a94-88e7-211036f612a1)

- [x] check that token is not refreshed for logged-out users 
  - log out of the app
  - In Developer Tools, go to **Application** > **Storage** > **Local storage** > `app name`, make sure `refreshTokenTimestamp` is not present
    -  if needed, [clear local storage](chrome://settings/clearBrowserData)
  - In Developer Tools, go to **Console**, and clear the console
  -  browse through the app (scroll down task list, click on profiles) and make sure there are no console errors for refresh attempts

- [x] remove token timestamp from storage when user logs out 
  - In Developer Tools, go to **Application** > **Storage** > **Local storage** > `app name`
  - sign in
  - check that `refreshTokenTimestamp` is added to local storage
  - sign out
  - check that `refreshTokenTimestamp` is removed from local storage
