### ISSUE TITLE
USER STORY: Style "not found" page

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#79]
As a **Developer**,

I want to **create a friendly and useful page for cases where the user's requested page was not found**,

so that **I can minimize interruptions in the user journey**

### Acceptance Criteria

1. The "not found" page has a friendly graphic
2. It as a link to the home page

### Tasks

- [x] create CSS for NotFound component
- [x] create `NotFound.js` component
  - display `NoResults` component
  - add link to home page
  - import CSS & adjust layout
- [x] in `App.js`, change route to use `NotFound` component: `<Route render={() => <NotFound />} />`
