### ISSUE TITLE
USER STORY: Indicate Logged-in User in Assignee list in TaskCreateForm

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#85]
As a **Logged-in User**,

I want to **see my username specially marked in the Assignee dropdown in the TaskCreateForm**,

so that **spot it faster**

### Acceptance Criteria

1. In the Assignee dropdown list in TaskCreateForm, the Logged-in User's name is highlighted (e.g. with "(me)" after it) 
2. It appears first in the list

### Tasks

- [x] `import { useCurrentUser } from "../../contexts/CurrentUserContext";`
- [x] define constant:   `const currentUser = useCurrentUser();`
- [x] add " (me)" to the displayed name of the user in the assignee dropdown:
  ```
   {currentUser?.username === profile.owner
       ?" (me)"
       :""
    }
  ```
