### ISSUE TITLE
USER STORY: Styling & responsivity of TaskCreateForm

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#86]
As a **Logged-in User**,

I want to **use a nicely styled and intuitively arranged form for creating tasks**,

so that **I can have a positive and efficient user experience**

### Acceptance Criteria

1. Fields are presented in order of importance, matching the TaskDetail page as much as suitable
2. Field arrangement is responsive
3. Button arrangement is responsive
4. Styling is consistent with the app's theme

### Tasks

- [x] update arrangement of fields 
- [x] make button placement responsive
- [x] make corners rounded

**Comment by blahosyl** [comment]
Blocked by #100
