### ISSUE TITLE
USER STORY: Styling & responsivity of task detail page

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#88]
As a **Logged-in User**,

I want to **use a nicely styled and intuitively arrange view of task details**,

so that **I can have a positive and efficient user experience**

### Acceptance Criteria

1. The task detail page displays information in order of salience & anticipating user actions: most to least salient from top to bottom of the page.
2. The page is responsive on all viewports in scope (min. width 320 px)
3. The page is styled in accordance with the rest of the app

### Tasks

- [x] style task title, excerpt & toggle
- [x] arrange assignee, status & priority – put them in the card header
- [x] display status in human readable format
- [x] display priority in human readable format
- [x] make title row responsive

![Image](https://github.com/user-attachments/assets/6da6c476-17c4-4a90-8ac9-f8b145d79c73)

- [x] put other fields in a list
- [x] put Watch icon in more prominent position
- [x] make Due date & Watch row responsive
- [x] style task owner row
  The `align-self-center` attribute of the [`Media` Bootstrap class](https://getbootstrap.com/docs/4.0/layout/media-object/) doesn't work, so used flexbox instead
- [x] change card color depending on priority
- [x] rounded borders: nearly done, blocked part in #91
