### ISSUE TITLE
USER STORY: Streamline Navbar items

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#89]
As a **Visitor**,

I want to **view Navbar items in thematic groups**,

so that **the Navbar is not overcrowded**

#### Navbar items for Logged-in Users

1. Logo
2. Create task (grouped with others)
3. Kanban
4. List
5.  Signout
6. Current user

#### Navbar items for Logged-out Users

1. Logo
2. Signin
3. Signup

### Tasks

- [x] make changes to Navbar items
- [x] move + with other Logged-In links
- [x] only expand Navbar on large screens and above
- [x] how short name in navbar
