### ISSUE TITLE
USER STORY: Deploy & connect FrontEnd app

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#9]
As an **Admin**,

I want to **deploy the FrontEnd app & connect it to the API**,

so that **I can develop and test the interaction of the 2 apps**

### Acceptance Criteria

1. The FrontEnd app is deployed
2. It interfaces with the API as intended

### Tasks

- [x] Connect FrontEnd Dev to API Prod
  - [x] install & set up Axios
  - [x] add FrontEnd Dev preview URL to API Prod config vars **without a trailing `/`**
- [x] Add `Procfile`
- [x] Deploy FrontEnd
- [x] Connect FrontEnd Prod to API Prod
  - [x] add FrontEnd Prod preview URL to API Prod config vars **without a trailing `/`**
