### ISSUE TITLE
USER STORY: Exclude logged-in user from Profile List

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#94]
As a **Logged-in User**,

I want to **view a list of my teammates withouth my profile in the list**,

so that **I do not see superfluous information**

### Acceptance Criteria

1. List of Profiles does **not** render the profile of the Logged-in User.

### Tasks

- [x] `import { useCurrentUser } from "../../contexts/CurrentUserContext";`
- [x] define constant:   `const currentUser = useCurrentUser();`
- [x] only render the whole component if a user is logged in
   ```
    currentUser && (
      <Container className={appStyles.Content}>
        ...
      <Container/>
    )
  ```
> [!CAUTION]  
> Deciding to change this  means the conditional inside the map has to be re-written to account for `currentUser` not existing.

- [x] only map users that are not the Current user:
  ```
  {profileList.results.map(
      (profile) =>
            profile && Number(profile.id) !== Number(currentUser.pk) && (
                  <Profile key={profile.id} profile={profile} />
           )
   )}
  ```
> [!IMPORTANT]  
> Since a profile is created each time a user registers, the primary key of these models will be the same for the same user. However, the relevant field is called `pk` in the `User` model (Allauth default) and `id` in the `Profile` model (custom written model).

**Comment by blahosyl** [comment]
Started development on new branch

**Comment by blahosyl** [comment]
[Merge pull request](https://github.com/blahosyl/task-manager-frontend/commit/1b857a17982f773d2637765c1455f21e7ad5ac99) https://github.com/blahosyl/task-manager-frontend/pull/97 [from blahosyl/dont-list-logged-in-user](https://github.com/blahosyl/task-manager-frontend/commit/1b857a17982f773d2637765c1455f21e7ad5ac99)
