### ISSUE TITLE
USER STORY: Dedicated fonts for the app

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/task-manager-frontend#99]
As a **Developer**,

I want to **use fonts that undescrore the theme of the app**,

so that **the user journey is enhanced**

### Acceptance Criteria

1. The app employs Google Fonts specifically selected for the purpose

### Tasks

- [x] make long list of font candidates
- [x] sort fonts into 3 groups
  - handwriting fonts, but good legibility
  - highly legible sans serif fonts with a retro (70ies) vibe
  - statement fonts (only used for titles and such)
- [x] Try different fonts, evaluate for
  - style & general impression
  - legibility
- [x] finalize font selection

**Comment by blahosyl** [comment]
Short list of fonts:



![Image](https://github.com/user-attachments/assets/3a262946-e18f-4398-ad39-448632b1741b)
![Image](https://github.com/user-attachments/assets/8dd1e0cc-f3cf-40b1-b36b-995436c05ce5)
![Image](https://github.com/user-attachments/assets/202a04b0-b40e-47dd-b3b5-65f673109381)
![Image](https://github.com/user-attachments/assets/50a683d2-e8c8-46f7-9572-da99817b2756)
![Image](https://github.com/user-attachments/assets/92df2e56-71e8-4ce7-9d9b-9870e1616068)
![Image](https://github.com/user-attachments/assets/e8c58da5-131a-44b9-99cd-9982ab7299bd)
![Image](https://github.com/user-attachments/assets/791cd025-141e-4b13-bdc8-68de4a436565)
![Image](https://github.com/user-attachments/assets/8c623b65-987f-4c70-b656-79263da14ebc)
![Image](https://github.com/user-attachments/assets/9d1f1b4e-fe56-45c4-b18c-165b984ae4f2)
![Image](https://github.com/user-attachments/assets/387165f9-4d3a-4256-a760-3740f50d5791)
![Image](https://github.com/user-attachments/assets/d9073495-fa04-472a-a71e-bc54981b47ef)
![Image](https://github.com/user-attachments/assets/c00e4e82-a5b1-4e2d-bab8-03b8b63e16e6)
![Image](https://github.com/user-attachments/assets/fe03a5a6-e606-4cae-a3c9-aebd8af2b29e)

**Comment by blahosyl** [comment]
Decided to use Kodchasan, as it evokes handwriting, while at the same time being very well legible.

In addition, this font has a wide selection of weights and styles.
